apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acme-dns.fullname" . }}
  labels:
    {{- include "acme-dns.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.cfg: |-
    {{- .Values.config | nindent 4 }}
